"""Scenery theme catalogs for the BasicScenarioGenerator.

Each theme maps shape-type keys (``rect``, ``circle``, ``polygon``)
to lists of descriptive names used when generating random scenography.
"""

from __future__ import annotations

SCENERY_THEMES: dict[str, dict[str, list[str]]] = {
    "urban": {
        "rect": [
            "Low ruins",
            "Stone wall",
            "Collapsed building",
            "Barricade",
            "Storage crates",
        ],
        "circle": [
            "Plaza fountain",
            "Fuel tank",
            "Radial monument",
            "Traffic roundabout",
            "Cooling silo",
        ],
        "polygon": [
            "Rubble field",
            "Collapsed plaza",
            "Broken pavement",
            "Urban debris",
            "Construction site",
        ],
    },
    "forest": {
        "rect": [
            "Hunting lodge",
            "Wooden palisade",
            "Abandoned cabin",
            "Rangers outpost",
            "Fallen log pile",
        ],
        "circle": [
            "Dense woods",
            "Sacred grove",
            "Thicket",
            "Mossy clearing",
            "Ancient tree ring",
        ],
        "polygon": [
            "Rocky ground",
            "Marshland",
            "Difficult terrain",
            "Thorny brush",
            "Wetland",
        ],
    },
    "desert": {
        "rect": [
            "Broken outpost",
            "Sandbag line",
            "Crumbling wall",
            "Supply depot",
            "Shelter ruins",
        ],
        "circle": [
            "Impact crater",
            "Dust bowl",
            "Sunken pit",
            "Dry well",
            "Oasis pool",
        ],
        "polygon": [
            "Rocky ridge",
            "Dune field",
            "Salt flats",
            "Scrap heap",
            "Scorched ground",
        ],
    },
    "shire": {
        "rect": [
            "Thatched cottage",
            "Stone hedge",
            "Market stall",
            "Barn",
            "Wooden fence",
        ],
        "circle": [
            "Village green",
            "Orchard grove",
            "Well",
            "Hobbit garden",
            "Flower ring",
        ],
        "polygon": [
            "Rolling hill",
            "Plowed field",
            "Footpath",
            "Farmland",
            "Meadow",
        ],
    },
    "rohan": {
        "rect": [
            "Riders camp",
            "Wooden palisade",
            "Horse stables",
            "Watch hut",
            "Supply wagons",
        ],
        "circle": [
            "Bonfire pit",
            "Horse corral",
            "Grass ring",
            "Training circle",
            "Meeting circle",
        ],
        "polygon": [
            "Rolling plain",
            "Wind swept ridge",
            "Tall grass",
            "Grazing field",
            "Rocky outcrop",
        ],
    },
    "gondor": {
        "rect": [
            "Guard post",
            "Stone bastion",
            "Broken wall",
            "Supply depot",
            "Barricade",
        ],
        "circle": [
            "Signal fire",
            "Fountain",
            "Statue base",
            "Well",
            "Courtyard",
        ],
        "polygon": [
            "Battle debris",
            "Broken causeway",
            "Rubble field",
            "Paved square",
            "Collapsed arch",
        ],
    },
    "minas_tirith": {
        "rect": [
            "White wall",
            "Guardhouse",
            "Gatehouse ruins",
            "Supply crates",
            "Barricade",
        ],
        "circle": [
            "Fountain",
            "Tower base",
            "Beacon brazier",
            "Courtyard",
            "Statue plinth",
        ],
        "polygon": [
            "Broken stairs",
            "Rubble field",
            "Collapsed terrace",
            "Paved square",
            "Shattered arch",
        ],
    },
    "osgiliath": {
        "rect": [
            "Broken bridge",
            "Collapsed hall",
            "Crumbling wall",
            "Stone pier",
            "Ruined tower",
        ],
        "circle": [
            "Sunken plaza",
            "Flooded pool",
            "Collapsed dome",
            "Fountain base",
            "Tower base",
        ],
        "polygon": [
            "River rubble",
            "Slick stone",
            "Shattered causeway",
            "Broken pavement",
            "Debris field",
        ],
    },
    "helms_deep": {
        "rect": [
            "Fortified wall",
            "Gatehouse",
            "Supply crates",
            "Barricade",
            "Siege debris",
        ],
        "circle": [
            "Culvert",
            "Signal fire",
            "Well",
            "Guard circle",
            "Training ring",
        ],
        "polygon": [
            "Rocky slope",
            "Broken ramp",
            "Debris field",
            "Rubble heap",
            "Stony ground",
        ],
    },
    "isengard": {
        "rect": [
            "Forge platform",
            "Wooden stockade",
            "Steel scaffolds",
            "Supply depot",
            "Barracks",
        ],
        "circle": [
            "Blast pit",
            "Water pool",
            "Engine base",
            "Signal fire",
            "Machinery ring",
        ],
        "polygon": [
            "Industrial debris",
            "Ashen ground",
            "Scrap heap",
            "Broken track",
            "Rubble field",
        ],
    },
    "mordor": {
        "rect": [
            "Dark watchtower",
            "Spiked palisade",
            "Broken wall",
            "Supply pens",
            "Slave pens",
        ],
        "circle": [
            "Lava pit",
            "Ash crater",
            "Dark well",
            "Signal fire",
            "Pit trap",
        ],
        "polygon": [
            "Ash field",
            "Scorched ground",
            "Jagged rocks",
            "Rubble heap",
            "Wasted land",
        ],
    },
    "moria": {
        "rect": [
            "Stone pillar",
            "Fallen arch",
            "Crumbling wall",
            "Ancient dais",
            "Broken gate",
        ],
        "circle": [
            "Well",
            "Chasm edge",
            "Rune circle",
            "Collapsed dome",
            "Deep pit",
        ],
        "polygon": [
            "Rubble field",
            "Broken walkway",
            "Rocky ground",
            "Shattered floor",
            "Debris pile",
        ],
    },
    "rivendell": {
        "rect": [
            "Elven pavilion",
            "Stone terrace",
            "Garden wall",
            "Rivendell bridge",
            "Archive ruins",
        ],
        "circle": [
            "Reflecting pool",
            "Sacred grove",
            "Fountain",
            "Sunwell",
            "Meeting circle",
        ],
        "polygon": [
            "Terraced garden",
            "Rocky streambed",
            "Shaded glade",
            "Leafy ground",
            "Broken steps",
        ],
    },
    "lothlorien": {
        "rect": [
            "Mallorn platform",
            "Wooden walkway",
            "Elven stair",
            "Garden wall",
            "Sentry post",
        ],
        "circle": [
            "Sacred grove",
            "Moonlit pool",
            "Tree ring",
            "Glade",
            "Shrine",
        ],
        "polygon": [
            "Leafy ground",
            "Mossy field",
            "Shaded glade",
            "Difficult terrain",
            "Fallen leaves",
        ],
    },
    "mirkwood": {
        "rect": [
            "Webbed ruins",
            "Fallen tree",
            "Wooden palisade",
            "Hunters camp",
            "Sentry post",
        ],
        "circle": [
            "Dark thicket",
            "Spider nest",
            "Poison pool",
            "Black grove",
            "Shadow ring",
        ],
        "polygon": [
            "Twisted roots",
            "Foggy ground",
            "Difficult terrain",
            "Rocky ground",
            "Deadfall",
        ],
    },
    "fangorn": {
        "rect": [
            "Ent shelter",
            "Wooden barricade",
            "Fallen log pile",
            "Abandoned camp",
            "Rangers post",
        ],
        "circle": [
            "Ancient grove",
            "Mossy clearing",
            "Spring",
            "Meeting circle",
            "Ring of stones",
        ],
        "polygon": [
            "Rocky ground",
            "Thorny brush",
            "Difficult terrain",
            "Wetland",
            "Forest floor",
        ],
    },
    "misty_mountains": {
        "rect": [
            "Stone outcrop",
            "Broken bridge",
            "Mountain shelter",
            "Watch post",
            "Ruined gate",
        ],
        "circle": [
            "Mountain lake",
            "Cave mouth",
            "Stone ring",
            "Cliff basin",
            "Glacial pool",
        ],
        "polygon": [
            "Rocky ridge",
            "Scree field",
            "Snowy ground",
            "Jagged rocks",
            "Steep slope",
        ],
    },
    "erebor": {
        "rect": [
            "Dwarven hall",
            "Stone pillar",
            "Forge platform",
            "Treasure vault",
            "Guard post",
        ],
        "circle": [
            "Great forge",
            "Anvil circle",
            "Rune circle",
            "Hot pit",
            "Well",
        ],
        "polygon": [
            "Broken walkway",
            "Rubble field",
            "Stone floor",
            "Collapsed stair",
            "Debris pile",
        ],
    },
    "dale": {
        "rect": [
            "Market stall",
            "Trade post",
            "Broken wall",
            "Guardhouse",
            "Barricade",
        ],
        "circle": [
            "Town square",
            "Fountain",
            "Well",
            "Signal fire",
            "Meeting circle",
        ],
        "polygon": [
            "Paved square",
            "Rubble field",
            "Broken street",
            "Collapsed plaza",
            "Debris field",
        ],
    },
}
